DECODER:
    HIDDEN_DIM: 256
    NHEADS: 8
    DIM_FFN: 1024
    FEATURE_LEVELS: 3
    DEC_BLOCKS: 3
    NUM_QUERIES: 100
    POS_ENC:
        MAX_FREQ: 10000
        DIMENSIONALITY: 3
        BASE: 2
