EXPERIMENT:
    ID: mask_pls

TRAIN:
    STEP: 80
    DECAY: 0.1
    LR: 0.0001
    MAX_EPOCH: 100
    BATCH_SIZE: 1
    BATCH_ACC: 4
    NUM_WORKERS: 6
    N_GPUS: -1

    AUG: True
    SUBSAMPLE: True

MODEL:
    DATASET: KITTI
    OVERLAP_THRESHOLD: 0.8

LOSS:
    WEIGHTS_KEYS: ['loss_ce','loss_dice','loss_mask']
    WEIGHTS: [2.0, 5.0, 5.0]
    EOS_COEF: 0.1
    NUM_POINTS: 50000 
    NUM_MASK_PTS: 500 # points to sample within each mask
    P_RATIO: 0.4 # ratio of total points to use for the matching
    SEM:
        WEIGHTS: [2,6] #Ce, Lovasz

KITTI:
    PATH: data/kitti
    CONFIG: datasets/semantic-kitti.yaml
    NUM_CLASSES: 20
    IGNORE_LABEL: 0
    MIN_POINTS: 10 #smallest mask
    SPACE: # coord limits
        [[-48.0,48.0],[-48.0,48.0],[-4.0,1.5]]
    SUB_NUM_POINTS: 80000

NUSCENES:
    PATH: data/nuscenes
    CONFIG: datasets/semantic-nuscenes.yaml
    NUM_CLASSES: 17
    IGNORE_LABEL: 0
    MIN_POINTS: 10 #smallest mask
    SPACE: # coord limits
        [[-50.0,50.0],[-50.0,50.0],[-5.0,3]]
    SUB_NUM_POINTS: 50000
